version: '2'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=PassW0rd1
      - MYSQL_DATABASE=camunda_db
      - MYSQL_USER=camunda
      - MYSQL_PASSWORD=Bpm123
    volumes:
      - ./mysql:/var/lib/mysql
